---
- hosts: all
  become: True

  tasks:
  - name: Install packeges
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - epel-release
      - yum-utils
      - python
      - python-pip

  - name: Apply new group without logout
    ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  - name: Enable and start docker
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Clone a repo
    ansible.builtin.git:
      repo: 'app'
      dest: /home/ec2-user
  
  - name: Build image and with build args
    ansible.builtin.shell: cd  /home/ec2-user/Jenkins-Final/src
    
  - name: Build image and with build args
    ansible.builtin.shell: docker build -t flask_app:latest .

  - name: Build image and with build args
    ansible.builtin.shell: docker push meitaltal/flask_app:latest
    
  - name: Run the flask app
    ansible.builtin.shell: docker run -d -p 5000:5000 --name web flask_app


  
  

  


