---
- hosts: all
  become: True

  tasks:
  - name: Install epel-release and yum-utils
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - epel-release
      - yum-utils

  - name: Install git, python-pip
    dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - git
      - python
      - python-pip

  - name: Apply new group without logout
    ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  - name: Enable and start docker
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Clone a repo
    ansible.builtin.git:
      repo: 'app'
      dest: /home/ec2-user
  
  - name: Build image and with build args
    ansible.builtin.shell: 
    cd  /home/ec2-user/Jenkins-Final/src
    docker build -t flask_app:latest .
    

  - name: Tag and push to docker hub
    community.docker.docker_image:
      name: flask_app
      repository: meitaltal/flask_app:v1
      push: true
      source: local

  - name: Run the flask app
    ansible.builtin.shell: docker run -d -p 5000:5000 --name web flask_app


  
  

  


