---
- hosts: all
  become: True

  tasks:
  - name: Install epel-release
    ansible.builtin.shell: sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E '%{rhel}').noarch.rpm -y
  
  - name: Install packeges
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - git
      - yum-utils
      - python
      - python-pip

  - name: add docker repo
    ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  - name: Enable and start docker
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Clone a repo
    ansible.builtin.git:
      repo: 'https://github.com/MeitalTalg/Jenkins-Final.git'
      dest: /home/ec2-user/Jenkins-Final
    

  - name: AWS ECR
    ansible.builtin.shell: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382545251.dkr.ecr.us-east-1.amazonaws.com"    
      
  - name: AWS build meital-repo
    ansible.builtin.shell: docker build -t meital-repo /home/ec2-user/Jenkins-Final/src

  - name: tag the image
    ansible.builtin.shell: docker tag meital-repo:latest 992382545251.dkr.ecr.us-east-1.amazonaws.com/meital-repo:latest

  - name: push the image to ECR
    ansible.builtin.shell: docker push 992382545251.dkr.ecr.us-east-1.amazonaws.com/meital-repo:latest
    
  - name: Run the flask app
    ansible.builtin.shell: docker run -d -p 5000:5000 --name web meital-repo

  
  

  


