---
- hosts: all
  become: True

  tasks:
  - name: remove epel-release and yum-utils
    yum:
      name: "{{ item }}"
      state: absent
     loop:
      - epel-release
      - yum-utils
      - git
      - python
      - python-pip

  - name: remove docker
    dnf:
      name: "{{ item }}"
      state: absent
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  
